(function(h){var n=window.AmazonUIPageJS||window.P,t=n._namespace||n.attributeErrors,b=t?t("CustomerReviewsCommonAssets"):n;b.guardFatal?b.guardFatal(h)(b,window):b.execute(function(){h(b,window)})})(function(h,n,t){h.when("A","cr-log-utils").register("cr-ajax-model",function(b,a){function c(a){e[a]&&(e[a].abort(),delete e[a])}function d(p,q,l,h,k,r,t){var w;w=r?r:g=g++;r=w;k=k?k:q.error||function(){};h=h?h:0;l=l?l:3;var D=q.finallyCallback||function(){};t||(t="reviewsAjax"+f++,n.uet&&n.uet("tc",
t));q.params.scope=t;q.contentType="application/x-www-form-urlencoded;charset=UTF-8";var B=q.success||function(){};q.success=function(a){delete e[r];"function"===typeof B&&B(a);"function"===typeof D&&D(a)};q.error=function(b){c(r);h++;h<l?(a.logError("AJAX Post to "+p+" failed, Attempt: "+h+" out of "+l,"WARN"),d(p,q,l,h,k,r,t)):(a.logError("AJAX Post to "+p+" from "+n.location.href+" failed, exhausted "+l+" attempts","FATAL"),"function"===typeof k&&k(b),"function"===typeof D&&D(b))};e[r]=b.post(p,
q);return r}var f=0,g=1,e={};return{abort:c,post:d}});h.when("A","jQuery").register("cr-A",function(b,a){var c={top:-100,left:-100};b.inView=function(b){b=b||a();if("function"===typeof b.offset){var f=(b.offset()||c).top-a(n).scrollTop();b=0<=f;f=f<a(n).height();return b&&f}return!1};b.onScreenAndVisible=function(){b.onScreen.apply(this,arguments)};return b});h.declare("reviews-constants",{PUSH_STATE:!0,REPLACE_STATE:!1,RATING_SERVICE_CONTEXT_ID:"ReviewsConsumption",data:{REFTAG:"data-reftag",
CSM_COUNTER:"data-csm-counter",getReviews:{STANDARD:"data-reviews-state-param",CHECKED:"data-reviews-param-checked",UNCHECKED:"data-reviews-param-unchecked"}},events:{CONTENT_CHANGED:"reviews:content-changed",RELOAD:"reviews:content-reload",RELOAD_COMPLETE:"reviews:content-reload-complete",AUTOSCROLL_COMPLETE:"reviews:autoscroll-complete",FILTER_FIRE_AGGREGATE:"reviews:filter-action:aggregate:trigger",FILTER_FIRE_UPDATE:"reviews:filter-action:trigger",FILTER_AGGREGATE:"reviews:filter-action:aggregate",
FILTER_PUSH:"reviews:filter-action:push-state",FILTER_REPLACE:"reviews:filter-action:replace-state",PAGINATION:"reviews:page-action",SEARCH_TEXTBOX:"reviews:search-textbox",SEARCH_BUTTON:"reviews:search-button",VOTE:"reviews:vote-action",TOGGLE_CLASS_CLICK:"reviews:toggle-class:click",FILTER_APPLY:"reviews:filter-action:apply",INPUT_COMMENT:"reviews:input-comment",SUBMIT_COMMENT:"reviews:submit-comment",OPEN_SUBMISSION_COMMENT:"reviews:open-comment-submission",SORT_COMMENTS:"reviews:sort-comments",
MORE_COMMENTS:"reviews:more-comments",EDIT_COMMENT:"reviews:edit-comment",CANCEL_EDIT_COMMENT:"reviews:cancel-edit-comment",DELETE_COMMENT:"reviews:delete-comment",SUBMIT_EDIT_COMMENT:"reviews:submit-edit-comment",MODIFY_EDIT_COMMENT:"reviews:modify-edit-comment",INPUT_PRODUCT_LINK:"reviews:input-product-link",SELECT_PRODUCT_LINK:"reviews:select-product-link",FEEDBACK_CLICK:"reviews:skyfall-feedback-click",CLIQUE_CLICK:"reviews:skyfall-clique-click",STAR_RATING_CLICK:"ryp:star-rating-click",STAR_RATING_CLEAR:"ryp:star-rating-clear-click"},
filterOptions:{SORT_KEY:"sortBy",HELPFUL:"helpful",RECENT:"recent",LEGACY_HELPFUL:"byRankDescending",LEGACY_RECENT:"bySubmissionDateDescending",MOBILE_HELPFUL:"sh",MOBILE_RECENT:"sd",STAR_KEY:"filterByStar",ALL_STARS:"all_stars",ONE_STAR:"one_star",TWO_STAR:"two_star",THREE_STAR:"three_star",FOUR_STAR:"four_star",FIVE_STAR:"five_star",POSTIVE:"positive",CRITICAL:"critical",FORMAT_KEY:"formatType",ALL_FORMATS:"all_formats",CURRENT_FORMAT:"current_format",AVP_KEY:"reviewerType",ALL_REVIEWS:"all_reviews",
AVP_ONLY:"avp_only_reviews"},keycodes:{ENTER:13,BACK_SPACE:8,SPACE:32},aui:{HIDDEN:"aok-hidden",NOWRAP:"aok-nowrap"}});h.when("A","cr-string-utils","cr-log-utils").register("cr-popup",function(b,a,c){function d(d){var g={};d&&d.data&&(g=d.data);var e=a.defaultIfBlank(g.url,d.$target.find("a").andSelf().filter("a").attr("href")),p=a.defaultIfBlank(g.title,"CustomerReviews"),p=""+p,q="";b.each({width:"500",height:"500",resizable:"1",scrollbars:"1",toolbar:"0",status:"1"},function(b,c){var d=
a.defaultIfBlank(g[c],b);q+=c+"="+d+","});var q=q.slice(0,-1),l=null;try{(l=n.open(e,p,q))?l.focus():c.logError("Unable to move focus to popup window with data: "+a.stringify(g),"ERROR"),d.$event.preventDefault()}catch(h){c.logError("Unable to open window with parameters: "+a.stringify(g),"FATAL",h)}return l}b.declarative("cr-popup",["click"],c.jsGuard(d));return{popup:d}});h.when("A","jQuery","reviews-constants").register("cr-generic-declarative-actions",function(b,a,c){function d(b){b&&
b.data&&b.data.selector&&b.data.cssClass&&b.$event&&"function"===typeof b.$event.preventDefault&&(a(b.data.selector).toggleClass(b.data.cssClass),b.$event.preventDefault())}b.declarative(c.events.TOGGLE_CLASS_CLICK,"click",d);return{toggleCssClass:d}});h.when("A","ready").register("cr-global-model",function(b){var a=b.state("reviews-page-state");a||(a=b.$("#cr-state-object").data("state"));var c=null;a&&(c=a.customerId);return{generateUrl:function(a,b){var c=a;c&&"/"!==c.charAt(c.length-
1)&&(c+="/");c&&b&&(c=c+"ref="+b);return c},isSignedIn:function(){return c?!0:!1}}});h.when("A","a-expander","jQuery","reviews-constants","cr-string-utils").register("cr-global-view",function(b,a,c,d,f){function g(a){var b="";if(a&&a.closest!==t){var c=a.closest("*["+h.REFTAG+"]");c&&(b=c.attr(h.REFTAG))}f.isBlank(b)&&a&&a.closest!==t&&(a=a.closest("*[rel]"))&&(b=a.attr("rel"));return f.defaultIfBlank(b,"cm_cr_unknown")}function e(a){return a&&"function"===typeof a.is?a.is("*["+h.getReviews.CHECKED+
"]")&&a.is("*["+h.getReviews.UNCHECKED+"]"):!1}function p(a){return a&&a.has!==t&&a.is!==t?0<a.find(":checked").length||a.is(":checked"):!1}function q(a,b){return a&&a.attr!==t&&b?f.parseJSON(a.attr(b))||{}:{}}function l(a){return a!==t}var h=d.data;b.on("a:expander:review_text_read_more:toggle:collapse",function(a){l(a)&&l(a.expander)&&l(a.expander.$expander)&&1===a.expander.$expander.length&&l(a.expander.$expander[0].closest(".review"))&&l(a.expander.$expander[0].closest(".review").offsetTop)&&
(a=a.expander.$expander[0].closest(".review").offsetTop,n.scroll(0,a))});b.on("a:pageUpdate",function(){l(a)&&a.initializeExpanders()});return{getReviewsStateParamsFromElement:function(a){var c=b.reduce(h.getReviews,function(a,b){return a+"*["+b+"],"},"").slice(0,-1),d;c&&a&&a.closest!==t&&(d=a.closest(c));return e(d)?p(d)?q(d,h.getReviews.CHECKED):q(d,h.getReviews.UNCHECKED):q(d,h.getReviews.STANDARD)},getReftag:function(a){var b;a&&a.$target&&(b=a.$target);a&&a.id&&(b=c("#"+a.id));a&&a.expander&&
a.expander.$expander&&(b=a.expander.$expander);b=g(b);"cm_cr_unknown"===b&&a&&a.data&&a.data.reftag&&(b=a.data.reftag);return b},getReftagByDom:g,scrollTo:function(a,b){var d=c(a).offset(),e=b||0,f=c("#cr-state-object").data("state"),f=f!==t&&f.disableScroll;d&&d.top!==t&&!f&&(c("html,body").stop(),c("html,body").animate({scrollTop:d.top-e},{queue:!1,duration:500}))}}});h.when("A").register("cr-log-utils",function(b){function a(a,b,c){n.ueLogError&&("string"!==typeof b&&(b="FATAL"),c?
n.ueLogError(c,{message:a,logLevel:b.toUpperCase(),attribution:"CustomerReviewsJS"}):n.ueLogError({message:a},{logLevel:b.toUpperCase(),attribution:"CustomerReviewsJS"}))}function c(a,b){return"string"===typeof b?b+a:"CustomerReviews:"+a}return{logError:a,jsGuard:function(b){if("function"===typeof b)return function(){try{return b.apply(this,arguments)}catch(c){a("Uncaught Error in function","FATAL",c)}};a("Unable to wrap non-function","ERROR");return b},incrementCount:function(a,b){if(n.ue){var g=
c(a,b),e=n.ue.count(g)||0;n.ue.count(g,e+1)}},logCount:function(a,b,g){n.ue&&(a=c(a,g),n.ue.count(a,b))}}});h.register("cr-mash-utils",function(){var b=!1;h.when("mash").execute(function(){b=!0});return{isMash:function(){return b}}});h.when("A","cr-log-utils").register("cr-number-utils",function(b,a){return{convertToInteger:function(b,d){if(b===parseInt(b,10))return b;if(null!==b&&b!==t&&""!==b)return parseInt(b.replace(/[^0-9]/g,""),10);if(d!==t)return d;a.logError("convertToInteger",
"Cannot convert "+b+" to Integer");return 0}}});h.when("cr-A","jQuery","cr-string-utils","afterReady").register("cr-on-view-utils",function(b,a,c){function d(a,c){if(!e[a]){var d=f(a,c)();p[a]=(p[a]||[]).concat(d);b.on.scroll(d)}}function f(c,d){return function k(){b.inView(a(c))&&(g(c,d),b.each(p[c]||[],function(a){b.off("scroll",a)}));return k}}function g(a,c){e[a]||(e[a]=!0,b.post(c.ajaxUrl,{params:c.ajaxParamsMap||{}}))}var e={},p={};b.each(a("*[data-cr-trigger-on-view]"),function(b,
e){var f=a(b),g=f.attr("data-cr-trigger-on-view"),g=c.parseJSON(g);if(null!==g){var p="cr-trigger-on-view-"+e;f.addClass(p);d("."+p,g)}});return{triggerOnScrollIntoView:d,trigger:g}});h.when("A","jQuery").register("cr-streaming-utils",function(b,a){return{appendFadeIn:function(c){if(null!==c&&2<c.length&&null!==c[1]&&null!==c[2]){var d=c[1];c=a(c[2]).hide();a(d).append(c);b.fadeIn(c,500,"ease-in-out",function(){})}}}});h.when("A","cr-log-utils").register("cr-string-utils",
function(b,a){function c(a){return null===a||a===t?!0:0===b.trim(a).length}return{defaultIfBlank:function(a,b){return c(a)?b:a},isBlank:c,parseJSON:function(c){try{return b.parseJSON(c)}catch(f){a.logError("Unable to parse JSON object","ERROR",f)}return null},startsWith:function(a,b){return a===b?!0:null===a||null===b?!1:0===a.indexOf(b)},stringify:function(a){return n.JSON&&n.JSON.stringify?n.JSON.stringify(a):a}}});h.when("A","cr-string-utils","3p-urijs").register("cr-uri-utils",function(b,
a,c){function d(){return c(n.location.href)}function f(){return d().query()}return{getCurrentUri:d,getCurrentQueryString:f,getCurrentQueryParameters:function(){return c.parseQuery(f())},isAmazonDomain:function(b){if("string"===typeof b||b instanceof String)b=c(b);var d=a.startsWith(b.domain(),"amazon");!1===d&&(b=b.hostname(),b=b.substring(b.indexOf(".")+1),d=a.startsWith(b,"amazon"));return d},setQueryParameters:function(d,e){if("string"===typeof d||d instanceof String)d=c(d);b.each(e,function(b,
c){a.isBlank(b)?d.removeSearch(c):d=d.setSearch(c,b)});return d},setReftag:function(b,d){if("string"===typeof b||b instanceof String)b=c(b);for(var f=b.segment(),h=!1,l=f.length-1;0<=l;l--)if(a.startsWith(f[l],"ref=")){h=!0;f[l]="ref="+d;break}h||f.push("ref="+d);b.segment(f);return b}}});h.when("cr-A","jQuery","cr-log-utils","cr-string-utils","afterReady").register("cr-weblab-utils",function(b,a,c,d){function f(d,e,f,n){p[e]||(c.logCount(f,0,n),d=g(a(d),e,f,n)(),h[e]=(h[e]||[]).concat(d),
b.on.scroll(d))}function g(a,c,d,f){return function w(){b.inView(a)&&(e(c,d,f),b.each(h[c]||[],function(a){b.off("scroll",a)}));return w}}function e(a,d,e){p[a]||(p[a]=!0,b.post("/ss/customer-reviews/ajax/weblab-trigger",{params:{weblabId:a}}),c.logCount(d,1,e))}var p={},h={};b.each(a("*[data-cr-weblab-trigger-on-scroll]"),function(b,c){var e=a(b),g=e.attr("data-cr-weblab-trigger-on-scroll"),g=d.parseJSON(g);if(null!==g){var p="cr-weblab-trigger-on-scroll-"+c;e.addClass(p);f("."+p,g.weblabId,g.metricName,
g.prefix)}});return{triggerOnScrollIntoView:f,triggerWeblab:e}});h.when("A").register("histogram-trigger",function(b){function a(){b.onScreen(b.$("#histogramTable"))&&b.trigger("scroll")}b.on.afterLoad(a);return{triggerHistogram:a}})});